name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 13.2.1
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
    - name: Build
      run: xcodebuild clean test -project "AppleWatchUIAnimation.xcodeproj" -scheme "AppleWatchUIAnimation" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run tests
      run: swift test -v
env:
   DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
